services:
  postgres:
    image: postgres:16
    container_name: shoppinglist-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: shoppinglist
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: 123
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: shoppinglist-api
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/shoppinglist
      SPRING_DATASOURCE_USERNAME: usr
      SPRING_DATASOURCE_PASSWORD: 123
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_FLYWAY_ENABLED: "true"
    restart: unless-stopped

volumes:
  pgdata: